// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG5UZtlqg16Fjr9QoeIuM_QlKREsgK6IA',
    appId: '1:753971544701:web:e059aa0b6488308cff6714',
    messagingSenderId: '753971544701',
    projectId: 'furniture-shop-devera',
    authDomain: 'furniture-shop-devera.firebaseapp.com',
    databaseURL: 'https://furniture-shop-devera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furniture-shop-devera.appspot.com',
    measurementId: 'G-FLTH4JFBB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHeKKymQEze7rZVFqPRK1ED5fyJv27ns',
    appId: '1:753971544701:android:dedde408a06a36caff6714',
    messagingSenderId: '753971544701',
    projectId: 'furniture-shop-devera',
    databaseURL: 'https://furniture-shop-devera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furniture-shop-devera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Be1QSiRIAliJr61R80lBd7MesczZoQI',
    appId: '1:753971544701:ios:38d6cb2294a66366ff6714',
    messagingSenderId: '753971544701',
    projectId: 'furniture-shop-devera',
    databaseURL: 'https://furniture-shop-devera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furniture-shop-devera.appspot.com',
    androidClientId: '753971544701-3tc9k9v4l1rmmihk0pkm8rtvmiiqvsf6.apps.googleusercontent.com',
    iosClientId: '753971544701-gqasdr4dk455qms94t718adnc270pev3.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureShopCustomersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Be1QSiRIAliJr61R80lBd7MesczZoQI',
    appId: '1:753971544701:ios:fc1a82bf9350dd4aff6714',
    messagingSenderId: '753971544701',
    projectId: 'furniture-shop-devera',
    databaseURL: 'https://furniture-shop-devera-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'furniture-shop-devera.appspot.com',
    androidClientId: '753971544701-3tc9k9v4l1rmmihk0pkm8rtvmiiqvsf6.apps.googleusercontent.com',
    iosClientId: '753971544701-kh8ejvqgfivb2hlqktg942rpjdllr27v.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureShopCustomersApp.RunnerTests',
  );
}
